notifications:
  email: false

language: node_js

node_js:
  - "node"

jdk:
  - openjdk8

addons:
  apt:
    packages:
      - ant

services:
  - docker

env:
  - img=existdb/existdb:latest
  - img=existdb/existdb:release
  - img=existdb/existdb:5.1.1

cache:
  npm: true
  directories:
    - ~/.cache

before_install:
  - docker pull $img
  - docker create --name exist-ci -p 8080:8080 $img


install:
  - npm ci
  - ant

before_script:
  # get crypto lib (enforce install order by name)
  - curl http://www.exist-db.org/exist/apps/public-repo/public/expath-crypto-module-1.0.0.xar --output aa-crypto.xar
  # copy xars to autodeploy
  - docker cp aa-crypto.xar exist-ci:exist/autodeploy
  - docker cp ./build/*.xar exist-ci:exist/autodeploy
  - docker start exist-ci
  # exist needs time
  - sleep 60
  - docker ps

script:
  - npm test

after_success:
  - docker stop exist-ci
